server:
  port: 8081
  
spring:
  application:    name: catalogService
    
# ribon 설정
# // customer 서비스 주소
#customerHost:
#  ribbon:
#    listOfServers: localhost:8082

# 유레카 서버+클라이언트 설정
eureka:
  instance:    prefer-ip-address: true
  client:    service-url:      defaultZone: http://localhost:8761/eureka  # default address 
   
    
    
    
    
    