server:
  port: 8888
  
spring:
  application:
    name: 
      -configClient01
      -configClient02
      
  profiles:
    active: native
  
  cloud:
    config:
      server:
        native:
          search-locations: classpath:configuration-repository/  #검색할 설정파일 경로
         
# actuator 설정, zuul 게이트웨이에 매핑된 경로, 필터들을 확인할 수 있는 엔드 포인트를 제공한다.
management:
#  endpoint:
#    routes:
#      enabled:  true
#    filters:
#      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
         