server:
  port: 8901

config:
  profile: profile 내용, configClient01-dev.yml 
  message: massage 내용, configClient01-dev.yml 파일 임포트
  
Globals:
  DbType: mysql
  DriverClassName: com.mysql.jdbc.Driver 
  Url: jdbc:mysql://127.0.0.1:3306/configClient01 
  UserName: com
  Password: com0

         